Repository CubeRT7/minirt, pull requests merged in 2023-07, with the labels that each got.

#20 refactory: element raw data to obj data
  src/Element/AmbientLight/ambient_light.h
  src/Element/AmbientLight/init_ambient_light.c
  src/Element/Camera/camera.h
  src/Element/Cylinder/cylinder.h
  src/Element/Cylinder/hit_cylinder.c
  src/Element/Cylinder/init_cylinder.c
  src/Element/Light/init_light.c
  src/Element/Light/light.h
  src/Element/Light/parse_light.c
  src/Element/Plane/hit_plane.c
  src/Element/Plane/init_plane.c
  src/Element/Plane/plane.h
  src/Element/Sphere/hit_sphere.c
  src/Element/Sphere/init_sphere.c
  src/Element/Sphere/sphere.h
  src/simulate/hook_draw.c
Labels: refactoring

#24 Refactor/import file
  src/Element/AmbientLight/ambient_light.c
  src/Element/AmbientLight/ambient_light.h
  src/Element/Camera/camera.c
  src/Element/Camera/camera.h
  src/Element/Camera/parse_camera.c
  src/Element/Cylinder/cylinder.c
  src/Element/Cylinder/cylinder.h
  src/Element/Light/light.c
  src/Element/Light/light.h
  src/Element/Plane/plane.h
  src/Element/Sphere/sphere.c
  src/Element/Sphere/sphere.h
  src/Element/common.h
  src/Makefile
  src/file/clean_rt.c
  src/file/file.h
  src/file/import_file.c
  src/file/parse_ambient_light.c
  src/file/parse_camera.c
  src/file/parse_cylinder.c
  src/file/parse_light.c
  src/file/parse_plane.c
  src/file/parse_sphere.c
  src/miniRT.c
  src/simulate/hook_draw.c
  src/simulate/simulate.c
  src/simulate/simulate.h
Labels: refactoring

#27 Refactor/element
  src/Element/AmbientLight/ambient_light.h
  src/Element/AmbientLight/hit_ambient_light.c
  src/Element/AmbientLight/init_ambient_light.c
  src/Element/Camera/camera.h
  src/Element/Camera/hit_camera.c
  src/Element/Camera/init_camera.c
  src/Element/Cylinder/cylinder.h
  src/Element/Cylinder/hit_cylinder.c
  src/Element/Cylinder/init_cylinder.c
  src/Element/Light/hit_light.c
  src/Element/Light/init_light.c
  src/Element/Light/light.h
  src/Element/Plane/init_plane.c
  src/Element/Plane/plane.h
  src/Element/Sphere/init_sphere.c
  src/Element/Sphere/sphere.h
  src/file/parse_ambient_light.c
  src/file/parse_camera.c
  src/file/parse_cylinder.c
  src/file/parse_light.c
  src/file/parse_plane.c
  src/file/parse_sphere.c
  src/simulate/hook_draw.c
Labels: refactoring

#29 fix: camera fov
  src/simulate/hook_draw.c
Labels: bug

#31 fix: hit cylinder bug
  src/Element/Cylinder/hit_cylinder.c
Labels: bug

#32 Refactor/element type
  src/Element/AmbientLight/ambient_light.c
  src/Element/AmbientLight/ambient_light.h
  src/Element/AmbientLight/init_ambient_light.c
  src/Element/Camera/camera.c
  src/Element/Camera/camera.h
  src/Element/Camera/init_camera.c
  src/Element/Camera/update_camera.c
  src/Element/Cylinder/cylinder.h
  src/Element/Cylinder/hit_cylinder.c
  src/Element/Cylinder/init_cylinder.c
  src/Element/Light/hit_light.c
  src/Element/Light/init_light.c
  src/Element/Light/light.c
  src/Element/Light/light.h
  src/Element/Plane/hit_plane.c
  src/Element/Plane/init_plane.c
  src/Element/Plane/plane.h
  src/Element/Sphere/hit_sphere.c
  src/Element/Sphere/init_sphere.c
  src/Element/Sphere/sphere.h
  src/Element/common.c
  src/Element/common.h
  src/Makefile
  src/simulate/hook_draw.c
  src/simulate/hook_key_event.c
  src/simulate/hook_mouse_event.c
  src/simulate/simulate.c
  src/simulate/util/simulate_util.h
  src/simulate/util/world_iter.c
Labels: refactoring

#33 Feat/v3 hadamard prod
  lib/libvector/Makefile
  lib/libvector/libvector.h
  lib/libvector/v3_hadamard_prod.c
  lib/libvector/v3_rotate_axis.c
Labels: enhancement

#35 Feature/camera
  data/coordination.rt
  src/Element/Camera/camera.h
  src/Element/Camera/init_camera.c
  src/simulate/hook_mouse_event.c
Labels: bug, enhancement

#37 fix: resize segment fault #21
  src/simulate/hook_draw.c
Labels: bug

#38 feat: check normalized vector3 in parse
  src/Element/common.c
  src/file/import_file.c
Labels: enhancement

#41 feat: float to str
  lib/libcustom/Makefile
  lib/libcustom/ft_ftoa.c
  lib/libcustom/libcustom.h
Labels: enhancement

#46 feat: separated drawing
  src/simulate/hook_draw.c
  src/simulate/simulate.c
  src/simulate/simulate.h
Labels: enhancement
