Repository CubeRT7/minirt, pull requests merged in 2023-06, with the labels that each got.

#11 Parse #10
  lib/libcustom/ft_strtof.c
  src/Element/AmbientLight/ambient_light.c
  src/Element/Camera/camera.c
  src/Element/Cylinder/cylinder.c
  src/Element/Light/light.c
  src/Element/Sphere/sphere.c
Labels: bug

#13 Refactory
  lib/Makefile
  lib/libgui/Makefile
  lib/libgui/gui_open_window.c
  lib/libgui/gui_setting.c
  lib/libgui/libgui.h
  src/Makefile
  src/miniRT.c
  src/parse/element.c
  src/parse/element.h
  src/parse/parse.c
  src/parse/parse.h
  src/simulate/hook.h
  src/simulate/hook_draw.c
  src/simulate/simulate.c
  src/simulate/simulate.h
Labels: refactoring

#14 Refactory
  src/miniRT.c
  src/simulate/simulate.c
  src/simulate/simulate.h
Labels: refactoring

#17 Refactor
  lib/libvector/Makefile
  src/Element/AmbientLight/ambient_light.c
  src/Element/AmbientLight/ambient_light.h
  src/Element/AmbientLight/parse_ambient_light.c
  src/Element/Camera/camera.c
  src/Element/Camera/camera.h
  src/Element/Camera/parse_camera.c
  src/Element/Cylinder/cylinder.c
  src/Element/Cylinder/cylinder.h
  src/Element/Cylinder/parse_cylinder.c
  src/Element/Light/light.c
  src/Element/Light/light.h
  src/Element/Light/parse_light.c
  src/Element/Plane/parse_plane.c
  src/Element/Plane/plane.c
  src/Element/Plane/plane.h
  src/Element/Sphere/parse_sphere.c
  src/Element/Sphere/sphere.c
  src/Element/Sphere/sphere.h
  src/Element/common.c
  src/Element/common.h
  src/Element/object.c
  src/Makefile
  src/file/file.h
  src/file/import_file.c
  src/miniRT.c
  src/parse/element.c
  src/parse/element.h
  src/parse/parse.c
  src/parse/parse.h
Labels: enhancement, refactoring
